# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.create(user_name: 'Admin', email: 'admin@example.com',password:"123456",password_confirmation:"123456", confirmed_at: Time.now.utc, first_name: "first name admin", last_name: "last name admin")
User.create(user_name: 'Test1', email: 'test1@example.com',password:"123456",password_confirmation:"123456", confirmed_at: Time.now.utc, first_name: "first name test1", last_name: "last name test1")
User.create(user_name: 'Test2', email: 'test2@example.com',password:"123456",password_confirmation:"123456", confirmed_at: Time.now.utc, first_name: "first name test2", last_name: "last name test2")


#Fourth year courses:
Course.create(code: "ECE444", name: "Software Engineering", year: 4, description: "The software development process. Software requirements and specifications. Software design techniques. Techniques for developing large software systems; CASE tools and software development environments. Software testing, documentation and maintenance.");
Course.create(code: "ECE421", name: "Introduction to Machine Learning", year: 4, description: "An Introduction to the basic theory, the fundamental algorithms, and the computational toolboxes of machine learning. The focus is on a balanced treatment of the practical and theoretical approaches, along with hands on experience with relevant software packages. Supervised learning methods covered in the course will include: the study of linear models for classification and regression, neural networks and support vector machines. Unsupervised learning methods covered in the course will include: principal component analysis, k-means clustering, and Gaussian mixture models. Theoretical topics will include:  bounds on the generalization error, bias-variance tradeoffs and the Vapnik-Chervonenkis (VC) dimension. Techniques to control overfitting, including regularization and validation, will be covered.");
Course.create(code: "ECE496", name: "Design Project", year: 4, description: "A full year capstone design project course intended to give students an opportunity to apply their technical knowledge and communication skills. Working in teams under the direct supervision of a faculty member, students develop a design project of their choice from an initial concept to a final working prototype. In the first session, a project proposal is submitted early on, followed by a project requirements specification. A design review meeting is then held to review the proposed design. Lectures given during the first session will develop expertise in various areas related to design and technical communication. In the second session, the teams present their work in a number of ways, including an oral presentation, a poster presentation, a final demonstration at the Design Fair, an individual progress report, and a group final report. Course deliverables are evaluated by both the team’s supervisor and one of several course administrators.");


#Third year courses
Course.create(code: "CSC384", name: " Introduction to Artificial Intelligence", year: 3, description: "Theories and algorithms that capture (or approximate) some of the core elements of computational intelligence. Topics include: search; logical representations and reasoning, classical automated planning, representing and reasoning with uncertainty, learning, decision making (planning) under uncertainty. Assignments provide practical experience, in both theory and programming, of the core.")
Course.create(code: "CSC343", name: " Introduction to Databases", year: 3, description: "Introduction to database management systems. The relational data model. Relational algebra. Querying and updating databases: the query language SQL. Application programming with SQL. Integrity constraints, normal forms, and database design. Elements of database system technology: query processing, transaction management.");
Course.create(code: "ECE302", name: "Probability and Applications", year: 3, description: "Events, sample space, axioms of probability. Discrete and continuous random variables, distribution and density functions. Bernoulli trials, Binomial, geometric, Poisson, exponential and Gaussian distributions.Expectation, moments, characteristic function and correlation coefficient.  Functions of random variables. Random vectors, joint distributions, transformations. Applications will be chosen from communication theory, estimation and hypothesis testing, predictive analytics and other areas of electrical and computer engineering.");

#second year courses
Course.create(code: "ECE216", name: "Signal and System", year: 2, description: "Fundamental discrete- and continuous-time signals, definition and properties of systems, linearity and time invariance, convolution, impulse response, differential and difference equations, Fourier analysis, sampling and aliasing, applications in communications.");
Course.create(code: "ECE221", name: "Electric and Magnetic Fields", year: 2, description: "The fundamental laws of electromagnetics are covered, including Coulomb's law, Gauss' law, Poisson's and Laplace's equations, the Biot-Savart law, Ampere's law, Faraday's law, and Maxwell's equations. Vector calculus is applied to determine the relationship between the electric and magnetic fields and their sources (charges and currents). The interaction of the fields with material media will be discussed, including resistance, polarization in dielectrics, magnetization in magnetic materials, properties of magnetic materials and boundary conditions. Other topics include: electric and magnetic forces, the electric potential, capacitance and inductance, electric and magnetic energy, magnetic circuits, and boundary-value problems.");
Course.create(code: "ECE231", name: "Introductory Electronics", year: 2, description: "An introduction to electronic circuits using operational amplifiers, diodes, bipolar junction transistors and field-effect transistors.");


#first year course
Course.create(code: "ECE101H1S", name: " Introduction to Electrical and Computer Engineering", year: 1, description: "This is a seminar series that will introduce first year students to the wealth of subjects within the field of Electrical and Computer Engineering. Instructors will be drawn from the various research groups within the Department. This course will be offered on a credit/no-credit basis. Credit will not be given to students who attend fewer than 70% of the seminars. Students who receive no credit for the course must re-take it in their 2F session. Students who have not received credit for this course at the end of their 2F session will not be permitted to register in session 2S.");
Course.create(code: "MAT185", name: "Linear Algebra", year: 1, description: "Topics include:  include: linear systems, matrix algebra, Rn as a vector space, a normed space and an inner-product space, linear transformations on Rn, eigenvalues, applications to circuits, mechanics and an introduction to computer methods.");
Course.create(code: "CIV100", name: "Mechanics", year: 1, description: "The principles of statics are applied to composition and resolution of forces, moments and couples. The equilibrium states of structures are examined. Throughout, the free body diagram concept is emphasized. Vector algebra is used where it is most useful, and stress blocks are introduced. Shear force diagrams, bending moment diagrams and stress-strain relationships for materials are discussed. Stress and deformation in axially loaded members and flexural members (beams) are also covered.");


